# Setup
title:        Tong TechBlog
tagline:      ê²€ì´ ì§§ìœ¼ë©´ í•œ ë°œì§ ë” ë‚˜ì•„ê°€ë¼ ğŸƒ
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       tongil Song
  url:        http://tong9433.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown